<a href="https://colab.research.google.com/github/Deenatnri1453/Python-Mini-Project/blob/main/intr_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
#Create a numpy array
# 1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)


[1 2 3 4 5]


In [3]:
# Creating 2D array - Matrix
arr2D = np.array([
[1,2,3],[4,5,6]
])
print(arr2D)


[[1 2 3]
 [4 5 6]]


In [4]:
# Creating arrays with default values

# Creating Matrix with all values of elements as '0'
allZeros = np.zeros((2,3))
print(allZeros)

# Creating Matrix with all values of elements as '1'
allOnes = np.ones((2,3))
print(allOnes)

# Creating Matrix with all values of elements as 'Constant values - n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [5]:
# Create an Identity Matrix - I

identity = np.eye(4)
print(identity)

# Indentity Matrix - Aii = 1 && Aij = 0
# For all A Belongs to R MxN
# Aij -

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [6]:
# Creating random Matrices

# with 0 & 1
rand1 = np.random.rand(3,3)
print(rand1)

# between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[0.16539135 0.47945    0.37911855]
 [0.1631908  0.44875774 0.41673115]
 [0.77588471 0.75991019 0.95867566]]
[[13 18 11]
 [13 16 12]
 [14 18 17]]


In [7]:
# Array Properties
arr = np.array([[1,2,3,4],[3,4,5,6]])
print(arr)

# Shape of array
print(f'\nThe shape of the array is {arr.shape}')

# Size of array
print(f'The size of the array is {arr.size}')

# Datatype of array
print(f'The Data type of the array is {arr.dtype}')

# Dimensions of array
print(f'The Dimension of the array is {arr.ndim}')

[[1 2 3 4]
 [3 4 5 6]]

The shape of the array is (2, 4)
The size of the array is 8
The Data type of the array is int64
The Dimension of the array is 2


In [8]:
# Indexing and Slicing

# Access the elements in ID Array

arr = np.array([1,2,3,8])
print(arr)
print(arr[2])

# Slicing the elements

print(arr[0:3])

# Access the elements in 2D Array
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
print(arr2[1,2])

 # first row with all columns
print(arr2[0,:])

# first column with all rows
print(arr2[:,0])

[1 2 3 8]
3
[1 2 3]
[[1 2 3]
 [4 5 6]]
6
[1 2 3]
[1 4]


In [9]:
#l1 =[]
#[l1.append(_) for _ in range(10)]

#print(l1)


l1 = np.arange(0,10)

print(l1)

l2 = np.arange(10,-0,-3)
print(l2)

[0 1 2 3 4 5 6 7 8 9]
[10  7  4  1]


In [10]:
#Mathmatical operations

a = np.array([1,2,3])
b = np.array([4,5,6])

print(f'The sum of a and b is {a+b}')
print(f'The diff of a and b is {a-b}')
print(f'The product of a and b is {a*b}')
print(f'The division of a and b is {a/b}')

The sum of a and b is [5 7 9]
The diff of a and b is [-3 -3 -3]
The product of a and b is [ 4 10 18]
The division of a and b is [0.25 0.4  0.5 ]


In [11]:
#Matrix multiplication
b1 = np.array([[1,2,3],[4,5,6]])
b2 = np.array([[5,6],[7,8],[1,3]])

# Dot product  ---- product = AB -- A m x n -- B n x p
c = np.dot(b1,b2)
print(c)

[[22 31]
 [61 82]]


In [ ]:
print(b1)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]


In [13]:
arr=np.array([[1,2,3],[4,5,6]])

In [14]:
type(arr)

numpy.ndarray

In [15]:
arr1 = np.random.randint(1,2,(3,1))

In [16]:
arr1.shape

(3, 1)

In [17]:
result = np.dot(arr,arr1)

In [18]:
print(result)

[[ 6]
 [15]]


In [19]:
r1 = np.random.randint(10,20,(3,3))
print(r1)

[[10 12 17]
 [19 15 12]
 [17 10 11]]


In [20]:
r2 = np.eye(3)
print(r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#r1 . I
result2 = np.dot(r1,r2)
print(result2)

[[10. 12. 17.]
 [19. 15. 12.]
 [17. 10. 11.]]


In [22]:
# M . I = I . M = M

# A . B != B . A


In [23]:
# Mathematical Operations
# + - * /

t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

print(t1)
print(t2)

[[5 3 4]
 [3 5 5]
 [5 3 5]]
[[5 5 3]
 [3 5 5]
 [4 3 5]]


In [24]:
t3 = t1 + t2
print(t3)

[[10  8  7]
 [ 6 10 10]
 [ 9  6 10]]


In [25]:
# Matrix multiplication
result = np.dot(arr,arr1)


In [26]:
# Statistical operation
mean = t3.mean()
max = t3.max()
median = np.median(t3)
std = np.std(t3)
var = np.var(t3)


In [27]:
print(mean)
print(max)
print(median)
print(std)
print(var)

8.444444444444445
10
9.0
1.640535895581489
2.691358024691358


In [28]:
std * std


2.6913580246913584

In [29]:
# Trignometric Functions

# sin(x)
# cos(x)
# ton(x) - sin(x) / cos(x)
# cosec - 1 / sin(x)
# sec - 1 / cos(x)
# cot - 1 / tan(x)

angles = np.array([0,15,30,45,60,75,90])

# Sin(array)

result = np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))


In [30]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [31]:
arr = np.array([1,2,3,4,5,6])

# Reshape the array
reshapedarr = arr.reshape(3,2)

print(reshapedarr)

# Convert / Flatter any n dim array
flattenedarr = arr.flatten()

print(flattenedarr)


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [32]:
# Stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

arr3 = np.vstack((arr1,arr2))
print(f"The shape of the arr3 is {arr3.shape}")

The shape of the arr3 is (2, 4)


In [33]:
# Stacking the data

arr1 = np.array([[1,2,3,4],[2,3,4,5]])
arr2 = np.array([10,20,30,40])

arr3 = np.vstack((arr1,arr2))
print(f"The shape of the arr3 is {arr3.shape}")



The shape of the arr3 is (3, 4)


In [34]:
# Stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])

# Vertical Stacking
arr3 = np.vstack((arr1,arr2))
print(f"The shape of the arr3 is {arr3.shape}")

# Horizantal Stacking
arr4 = np.hstack((arr1,arr2))
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)


The shape of the arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [35]:
# Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr >= 40]

print(farr)

[40 50 60 70 80]
